In [10]:
import os
import mlflow
from dotenv import load_dotenv

load_dotenv()

TABLE_NAME = "users_churn"  # таблица с данными в postgres

TRACKING_SERVER_HOST = "127.0.0.1"
TRACKING_SERVER_PORT = 5003

EXPERIMENT_NAME = "EDA_EXPERIMENT"  # напишите название вашего эксперимента
RUN_NAME = "eda_run2"

ASSETS_DIR = "assets"

os.environ["MLFLOW_S3_ENDPOINT_URL"] = "https://storage.yandexcloud.net"
os.environ["AWS_ACCESS_KEY_ID"] = os.getenv("AWS_ACCESS_KEY_ID")
os.environ["AWS_SECRET_ACCESS_KEY"] = os.getenv("AWS_SECRET_ACCESS_KEY")

mlflow.set_tracking_uri(
    f"http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}"
)
mlflow.set_registry_uri(
    f"http://{TRACKING_SERVER_HOST}:{TRACKING_SERVER_PORT}"
)

experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME)
if not experiment_id:
    experiment_id = mlflow.create_experiment(EXPERIMENT_NAME)
    experiment_id = mlflow.get_experiment_by_name(EXPERIMENT_NAME)


with mlflow.start_run(
    run_name=RUN_NAME, experiment_id=experiment_id.experiment_id
) as run:
    run_id = run.info.run_id

    mlflow.log_artifacts(ASSETS_DIR)

🏃 View run eda_run2 at: http://127.0.0.1:5003/#/experiments/12/runs/f1c5c2a42e7a45e28df8fda5f8022c11
🧪 View experiment at: http://127.0.0.1:5003/#/experiments/12


In [8]:
from dotenv import load_dotenv

load_dotenv()

print(os.getenv("S3_BUCKET_NAME"))

s3-student-mle-20260614-fb07c65e05


In [ ]:
import pandas as pd
import numpy as np
from datetime import timedelta

np.random.seed(42)
np.random.default_rng(42)
# генерация данных для каждого столбца
data = {
    "temperature_celsius": np.random.uniform(
        20, 35, size=100
    ),  # температура в градусах Цельсия (float)
    "age_years": np.random.randint(18, 65, size=100),  # возраст в годах (int)
    "timestamp_event": [
        pd.Timestamp("20230101") + timedelta(days=i) for i in range(100)
    ],  # время события (datetime)
    "product_category": np.random.choice(
        ["electronics", "clothing", "food"], size=100
    ),  # категория продукта (string)
    "is_purchased": np.random.choice(
        [True, False], size=100
    ),  # булевое значение приобретения (bool)
    "humidity_percentage": np.random.uniform(
        40, 80, size=100
    ),  # влажность в процентах (float)
    "income_usd": np.random.randint(
        20000, 100000, size=100
    ),  # доход в долларах США (int)
    "last_updated": [
        pd.Timestamp("20240101") + timedelta(days=i) for i in range(100)
    ],  # последнее обновление (datetime)
    "product_name": [
        "Product_" + str(i) for i in range(100)
    ],  # название продукта (string)
    "is_subscribed": np.random.choice(
        [True, False], size=100
    ),  # булевое значение подписки (bool)
}

# создание DataFrame
df = pd.DataFrame(data)

# ваш код здесь #
print(df.dtypes)
df_int = df.select_dtypes(include=["int64"])
df_float = df.select_dtypes(include=["float64"])
df_bool = df.select_dtypes(include=["bool"])
df_datetime = df.select_dtypes(include=["datetime64[ns]"])
df_object = df.select_dtypes(include=["object"])

temperature_celsius           float64
age_years                       int64
timestamp_event        datetime64[ns]
product_category               object
is_purchased                     bool
humidity_percentage           float64
income_usd                      int64
last_updated           datetime64[ns]
product_name                   object
is_subscribed                    bool
dtype: object


In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

data = np.array(["Универсал", "Седан", "Универсал", "Хэтчбек"]).reshape(-1, 1)
print(data)
encoder = OneHotEncoder()
encoded_data = encoder.fit_transform(data).toarray()
print(encoded_data)

[['Универсал']
 ['Седан']
 ['Универсал']
 ['Хэтчбек']]
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
